export enum ActionTypes {
  SET_CHATS = "SET_CHATS",
  CREATE_CHAT = "CREATE_CHAT",
  EDIT_CHAT = "EDIT_CHAT",
  DELETE_CHAT = "DELETE_CHAT",
  GET_CHATS = "GET_CHATS",
  CONNECT_CHAT = "CONNECT_CHAT",
}
